app:
  use-queue: true
  clients:
    github-url: "https://api.github.com"
    github-api-token: ${GITHUB_API_TOKEN}
    stackoverflow-url: "https://api.stackexchange.com"
    bot-url: "http://localhost:8090"
  scheduler:
    enable: true
    interval: 30s
    force-check-delay: 30s
  database-access-type: JPA
  kafka:
    enabled: true
    topic-name: "LinkUpdates"
  retry-politics:
    max-attempts: 3
    status-codes: 408, 425, 503, 504, 522, 524
    type: CONSTANT
    config:
      constant:
        back-off-period: 1000
      linear:
        initial-interval: 1000
        max-interval: 5000
      exponential:
        initial-interval: 1000
        mult: 2
        max-interval: 100000

spring:
  application:
    name: scrapper
  datasource:
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    show-sql: false
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000, expireAfterAccess=90s
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
  kafka:
    bootstrap-servers: "localhost:9092"

bucket4j:
  enabled: false
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - bandwidths:
            - capacity: 30
              refill-capacity: 30
              time: 2
              unit: seconds
              initial-capacity: 30
              refill-speed: interval

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
