/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables.records;

import edu.java.scrapper.domain.jooq.tables.ChatLinkAssignment;
import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatLinkAssignmentRecord extends TableRecordImpl<ChatLinkAssignmentRecord>
    implements Record2<String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHAT_LINK_ASSIGNMENT.CHAT_ID</code>.
     */
    public void setChatId(@Nullable String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CHAT_LINK_ASSIGNMENT.CHAT_ID</code>.
     */
    @Size(max = 20)
    @Nullable
    public String getChatId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CHAT_LINK_ASSIGNMENT.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>CHAT_LINK_ASSIGNMENT.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return ChatLinkAssignment.CHAT_LINK_ASSIGNMENT.CHAT_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return ChatLinkAssignment.CHAT_LINK_ASSIGNMENT.LINK_ID;
    }

    @Override
    @Nullable
    public String component1() {
        return getChatId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getLinkId();
    }

    @Override
    @Nullable
    public String value1() {
        return getChatId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public ChatLinkAssignmentRecord value1(@Nullable String value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatLinkAssignmentRecord value2(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatLinkAssignmentRecord values(@Nullable String value1, @Nullable Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatLinkAssignmentRecord
     */
    public ChatLinkAssignmentRecord() {
        super(ChatLinkAssignment.CHAT_LINK_ASSIGNMENT);
    }

    /**
     * Create a detached, initialised ChatLinkAssignmentRecord
     */
    @ConstructorProperties({"chatId", "linkId"})
    public ChatLinkAssignmentRecord(@Nullable String chatId, @Nullable Long linkId) {
        super(ChatLinkAssignment.CHAT_LINK_ASSIGNMENT);

        setChatId(chatId);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatLinkAssignmentRecord
     */
    public ChatLinkAssignmentRecord(edu.java.scrapper.domain.jooq.tables.pojos.ChatLinkAssignment value) {
        super(ChatLinkAssignment.CHAT_LINK_ASSIGNMENT);

        if (value != null) {
            setChatId(value.getChatId());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }
}
