/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables.records;

import edu.java.scrapper.domain.jooq.tables.Link;
import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements
    Record11<Long, String, String, LocalDateTime, LocalDateTime, String, String, String, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINK.URI</code>.
     */
    public void setUri(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK.URI</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 256)
    @NotNull
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINK.DESCRIPTION</code>.
     */
    public void setDescription(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINK.DESCRIPTION</code>.
     */
    @Size(max = 128)
    @Nullable
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>LINK.CREATED_AT</code>.
     */
    public void setCreatedAt(@Nullable LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINK.CREATED_AT</code>.
     */
    @Nullable
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>LINK.UPDATED_AT</code>.
     */
    public void setUpdatedAt(@Nullable LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>LINK.UPDATED_AT</code>.
     */
    @Nullable
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>LINK.CREATED_BY</code>.
     */
    public void setCreatedBy(@Nullable String value) {
        set(5, value);
    }

    /**
     * Getter for <code>LINK.CREATED_BY</code>.
     */
    @Size(max = 64)
    @Nullable
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>LINK.UPDATED_BY</code>.
     */
    public void setUpdatedBy(@Nullable String value) {
        set(6, value);
    }

    /**
     * Getter for <code>LINK.UPDATED_BY</code>.
     */
    @Size(max = 64)
    @Nullable
    public String getUpdatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>LINK.TITLE</code>.
     */
    public void setTitle(@Nullable String value) {
        set(7, value);
    }

    /**
     * Getter for <code>LINK.TITLE</code>.
     */
    @Size(max = 128)
    @Nullable
    public String getTitle() {
        return (String) get(7);
    }

    /**
     * Setter for <code>LINK.ETAG</code>.
     */
    public void setEtag(@Nullable String value) {
        set(8, value);
    }

    /**
     * Getter for <code>LINK.ETAG</code>.
     */
    @Size(max = 256)
    @Nullable
    public String getEtag() {
        return (String) get(8);
    }

    /**
     * Setter for <code>LINK.LAST_CHECKED_AT</code>.
     */
    public void setLastCheckedAt(@Nullable LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>LINK.LAST_CHECKED_AT</code>.
     */
    @Nullable
    public LocalDateTime getLastCheckedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>LINK.TYPE</code>.
     */
    public void setType(@Nullable String value) {
        set(10, value);
    }

    /**
     * Getter for <code>LINK.TYPE</code>.
     */
    @Size(max = 16)
    @Nullable
    public String getType() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row11<Long, String, String, LocalDateTime, LocalDateTime, String, String, String, String, LocalDateTime, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row11<Long, String, String, LocalDateTime, LocalDateTime, String, String, String, String, LocalDateTime, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Link.LINK.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Link.LINK.URI;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return Link.LINK.DESCRIPTION;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field4() {
        return Link.LINK.CREATED_AT;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field5() {
        return Link.LINK.UPDATED_AT;
    }

    @Override
    @NotNull
    public Field<String> field6() {
        return Link.LINK.CREATED_BY;
    }

    @Override
    @NotNull
    public Field<String> field7() {
        return Link.LINK.UPDATED_BY;
    }

    @Override
    @NotNull
    public Field<String> field8() {
        return Link.LINK.TITLE;
    }

    @Override
    @NotNull
    public Field<String> field9() {
        return Link.LINK.ETAG;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field10() {
        return Link.LINK.LAST_CHECKED_AT;
    }

    @Override
    @NotNull
    public Field<String> field11() {
        return Link.LINK.TYPE;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getUri();
    }

    @Override
    @Nullable
    public String component3() {
        return getDescription();
    }

    @Override
    @Nullable
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    @Nullable
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    @Nullable
    public String component6() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public String component7() {
        return getUpdatedBy();
    }

    @Override
    @Nullable
    public String component8() {
        return getTitle();
    }

    @Override
    @Nullable
    public String component9() {
        return getEtag();
    }

    @Override
    @Nullable
    public LocalDateTime component10() {
        return getLastCheckedAt();
    }

    @Override
    @Nullable
    public String component11() {
        return getType();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getUri();
    }

    @Override
    @Nullable
    public String value3() {
        return getDescription();
    }

    @Override
    @Nullable
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    @Nullable
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    @Nullable
    public String value6() {
        return getCreatedBy();
    }

    @Override
    @Nullable
    public String value7() {
        return getUpdatedBy();
    }

    @Override
    @Nullable
    public String value8() {
        return getTitle();
    }

    @Override
    @Nullable
    public String value9() {
        return getEtag();
    }

    @Override
    @Nullable
    public LocalDateTime value10() {
        return getLastCheckedAt();
    }

    @Override
    @Nullable
    public String value11() {
        return getType();
    }

    @Override
    @NotNull
    public LinkRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value2(@NotNull String value) {
        setUri(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value3(@Nullable String value) {
        setDescription(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value4(@Nullable LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value5(@Nullable LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value6(@Nullable String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value7(@Nullable String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value8(@Nullable String value) {
        setTitle(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value9(@Nullable String value) {
        setEtag(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value10(@Nullable LocalDateTime value) {
        setLastCheckedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value11(@Nullable String value) {
        setType(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord values(
        @Nullable Long value1,
        @NotNull String value2,
        @Nullable String value3,
        @Nullable LocalDateTime value4,
        @Nullable LocalDateTime value5,
        @Nullable String value6,
        @Nullable String value7,
        @Nullable String value8,
        @Nullable String value9,
        @Nullable LocalDateTime value10,
        @Nullable String value11
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    @ConstructorProperties({"id", "uri", "description", "createdAt", "updatedAt", "createdBy", "updatedBy", "title",
        "etag", "lastCheckedAt", "type"})
    public LinkRecord(
        @Nullable Long id,
        @NotNull String uri,
        @Nullable String description,
        @Nullable LocalDateTime createdAt,
        @Nullable LocalDateTime updatedAt,
        @Nullable String createdBy,
        @Nullable String updatedBy,
        @Nullable String title,
        @Nullable String etag,
        @Nullable LocalDateTime lastCheckedAt,
        @Nullable String type
    ) {
        super(Link.LINK);

        setId(id);
        setUri(uri);
        setDescription(description);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setTitle(title);
        setEtag(etag);
        setLastCheckedAt(lastCheckedAt);
        setType(type);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(edu.java.scrapper.domain.jooq.tables.pojos.Link value) {
        super(Link.LINK);

        if (value != null) {
            setId(value.getId());
            setUri(value.getUri());
            setDescription(value.getDescription());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setTitle(value.getTitle());
            setEtag(value.getEtag());
            setLastCheckedAt(value.getLastCheckedAt());
            setType(value.getType());
            resetChangedOnNotNull();
        }
    }
}
