/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables.records;

import edu.java.scrapper.domain.jooq.tables.TgChat;
import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TgChatRecord extends UpdatableRecordImpl<TgChatRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TG_CHAT.ID</code>.
     */
    public void setId(@NotNull String value) {
        set(0, value);
    }

    /**
     * Getter for <code>TG_CHAT.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 20)
    @NotNull
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>TG_CHAT.DIALOG_STATE</code>.
     */
    public void setDialogState(@Nullable String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TG_CHAT.DIALOG_STATE</code>.
     */
    @Size(max = 16)
    @Nullable
    public String getDialogState() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TG_CHAT.LANGUAGE_TAG</code>.
     */
    public void setLanguageTag(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TG_CHAT.LANGUAGE_TAG</code>.
     */
    @Size(max = 4)
    @Nullable
    public String getLanguageTag() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return TgChat.TG_CHAT.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return TgChat.TG_CHAT.DIALOG_STATE;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return TgChat.TG_CHAT.LANGUAGE_TAG;
    }

    @Override
    @NotNull
    public String component1() {
        return getId();
    }

    @Override
    @Nullable
    public String component2() {
        return getDialogState();
    }

    @Override
    @Nullable
    public String component3() {
        return getLanguageTag();
    }

    @Override
    @NotNull
    public String value1() {
        return getId();
    }

    @Override
    @Nullable
    public String value2() {
        return getDialogState();
    }

    @Override
    @Nullable
    public String value3() {
        return getLanguageTag();
    }

    @Override
    @NotNull
    public TgChatRecord value1(@NotNull String value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public TgChatRecord value2(@Nullable String value) {
        setDialogState(value);
        return this;
    }

    @Override
    @NotNull
    public TgChatRecord value3(@Nullable String value) {
        setLanguageTag(value);
        return this;
    }

    @Override
    @NotNull
    public TgChatRecord values(@NotNull String value1, @Nullable String value2, @Nullable String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TgChatRecord
     */
    public TgChatRecord() {
        super(TgChat.TG_CHAT);
    }

    /**
     * Create a detached, initialised TgChatRecord
     */
    @ConstructorProperties({"id", "dialogState", "languageTag"})
    public TgChatRecord(@NotNull String id, @Nullable String dialogState, @Nullable String languageTag) {
        super(TgChat.TG_CHAT);

        setId(id);
        setDialogState(dialogState);
        setLanguageTag(languageTag);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TgChatRecord
     */
    public TgChatRecord(edu.java.scrapper.domain.jooq.tables.pojos.TgChat value) {
        super(TgChat.TG_CHAT);

        if (value != null) {
            setId(value.getId());
            setDialogState(value.getDialogState());
            setLanguageTag(value.getLanguageTag());
            resetChangedOnNotNull();
        }
    }
}
