/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables.pojos;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TgChat implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String dialogState;
    private String languageTag;

    public TgChat() {
    }

    public TgChat(TgChat value) {
        this.id = value.id;
        this.dialogState = value.dialogState;
        this.languageTag = value.languageTag;
    }

    @ConstructorProperties({"id", "dialogState", "languageTag"})
    public TgChat(
        @NotNull String id,
        @Nullable String dialogState,
        @Nullable String languageTag
    ) {
        this.id = id;
        this.dialogState = dialogState;
        this.languageTag = languageTag;
    }

    /**
     * Getter for <code>TG_CHAT.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 20)
    @NotNull
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>TG_CHAT.ID</code>.
     */
    public void setId(@NotNull String id) {
        this.id = id;
    }

    /**
     * Getter for <code>TG_CHAT.DIALOG_STATE</code>.
     */
    @Size(max = 16)
    @Nullable
    public String getDialogState() {
        return this.dialogState;
    }

    /**
     * Setter for <code>TG_CHAT.DIALOG_STATE</code>.
     */
    public void setDialogState(@Nullable String dialogState) {
        this.dialogState = dialogState;
    }

    /**
     * Getter for <code>TG_CHAT.LANGUAGE_TAG</code>.
     */
    @Size(max = 4)
    @Nullable
    public String getLanguageTag() {
        return this.languageTag;
    }

    /**
     * Setter for <code>TG_CHAT.LANGUAGE_TAG</code>.
     */
    public void setLanguageTag(@Nullable String languageTag) {
        this.languageTag = languageTag;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TgChat other = (TgChat) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.dialogState == null) {
            if (other.dialogState != null) {
                return false;
            }
        } else if (!this.dialogState.equals(other.dialogState)) {
            return false;
        }
        if (this.languageTag == null) {
            if (other.languageTag != null) {
                return false;
            }
        } else if (!this.languageTag.equals(other.languageTag)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.dialogState == null) ? 0 : this.dialogState.hashCode());
        result = prime * result + ((this.languageTag == null) ? 0 : this.languageTag.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TgChat (");

        sb.append(id);
        sb.append(", ").append(dialogState);
        sb.append(", ").append(languageTag);

        sb.append(")");
        return sb.toString();
    }
}
