/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables;

import edu.java.scrapper.domain.jooq.DefaultSchema;
import edu.java.scrapper.domain.jooq.Keys;
import edu.java.scrapper.domain.jooq.tables.records.ChatLinkAssignmentRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatLinkAssignment extends TableImpl<ChatLinkAssignmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CHAT_LINK_ASSIGNMENT</code>
     */
    public static final ChatLinkAssignment CHAT_LINK_ASSIGNMENT = new ChatLinkAssignment();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ChatLinkAssignmentRecord> getRecordType() {
        return ChatLinkAssignmentRecord.class;
    }

    /**
     * The column <code>CHAT_LINK_ASSIGNMENT.CHAT_ID</code>.
     */
    public final TableField<ChatLinkAssignmentRecord, String> CHAT_ID =
        createField(DSL.name("CHAT_ID"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>CHAT_LINK_ASSIGNMENT.LINK_ID</code>.
     */
    public final TableField<ChatLinkAssignmentRecord, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT, this, "");

    private ChatLinkAssignment(Name alias, Table<ChatLinkAssignmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChatLinkAssignment(Name alias, Table<ChatLinkAssignmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CHAT_LINK_ASSIGNMENT</code> table reference
     */
    public ChatLinkAssignment(String alias) {
        this(DSL.name(alias), CHAT_LINK_ASSIGNMENT);
    }

    /**
     * Create an aliased <code>CHAT_LINK_ASSIGNMENT</code> table reference
     */
    public ChatLinkAssignment(Name alias) {
        this(alias, CHAT_LINK_ASSIGNMENT);
    }

    /**
     * Create a <code>CHAT_LINK_ASSIGNMENT</code> table reference
     */
    public ChatLinkAssignment() {
        this(DSL.name("CHAT_LINK_ASSIGNMENT"), null);
    }

    public <O extends Record> ChatLinkAssignment(Table<O> child, ForeignKey<O, ChatLinkAssignmentRecord> key) {
        super(child, key, CHAT_LINK_ASSIGNMENT);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<ForeignKey<ChatLinkAssignmentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_2A, Keys.CONSTRAINT_2A7);
    }

    private transient TgChat _tgChat;
    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.TG_CHAT</code> table.
     */
    public TgChat tgChat() {
        if (_tgChat == null) {
            _tgChat = new TgChat(this, Keys.CONSTRAINT_2A);
        }

        return _tgChat;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null) {
            _link = new Link(this, Keys.CONSTRAINT_2A7);
        }

        return _link;
    }

    @Override
    @NotNull
    public ChatLinkAssignment as(String alias) {
        return new ChatLinkAssignment(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public ChatLinkAssignment as(Name alias) {
        return new ChatLinkAssignment(alias, this);
    }

    @Override
    @NotNull
    public ChatLinkAssignment as(Table<?> alias) {
        return new ChatLinkAssignment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLinkAssignment rename(String name) {
        return new ChatLinkAssignment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLinkAssignment rename(Name name) {
        return new ChatLinkAssignment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatLinkAssignment rename(Table<?> name) {
        return new ChatLinkAssignment(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
