/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq;

import edu.java.scrapper.domain.jooq.tables.ChatLinkAssignment;
import edu.java.scrapper.domain.jooq.tables.Link;
import edu.java.scrapper.domain.jooq.tables.TgChat;
import edu.java.scrapper.domain.jooq.tables.records.ChatLinkAssignmentRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinkRecord;
import edu.java.scrapper.domain.jooq.tables.records.TgChatRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinkRecord> CONSTRAINT_2 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] {Link.LINK.URI}, true);
    public static final UniqueKey<TgChatRecord> CONSTRAINT_D =
        Internal.createUniqueKey(TgChat.TG_CHAT, DSL.name("CONSTRAINT_D"), new TableField[] {TgChat.TG_CHAT.ID}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkAssignmentRecord, TgChatRecord> CONSTRAINT_2A = Internal.createForeignKey(
        ChatLinkAssignment.CHAT_LINK_ASSIGNMENT,
        DSL.name("CONSTRAINT_2A"),
        new TableField[] {ChatLinkAssignment.CHAT_LINK_ASSIGNMENT.CHAT_ID},
        Keys.CONSTRAINT_D,
        new TableField[] {TgChat.TG_CHAT.ID},
        true
    );
    public static final ForeignKey<ChatLinkAssignmentRecord, LinkRecord> CONSTRAINT_2A7 = Internal.createForeignKey(
        ChatLinkAssignment.CHAT_LINK_ASSIGNMENT,
        DSL.name("CONSTRAINT_2A7"),
        new TableField[] {ChatLinkAssignment.CHAT_LINK_ASSIGNMENT.LINK_ID},
        Keys.CONSTRAINT_2,
        new TableField[] {Link.LINK.ID},
        true
    );
}
